version: "3.5"
services:
  eureka-server:
    image: eu.gcr.io/stdstack/eureka-server:0.1
    container_name: stdstack-eureka-server
    ports:
      - "8761:8761"
  config-server:
    image: eu.gcr.io/stdstack/config-server:0.1
    container_name: stdstack-config-server
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
    healthcheck:
      test: nc -v -w 5 -z stdstack-config-server 9000
      interval: 5s
      timeout: 3s
      retries: 10
  auth-server:
    image: eu.gcr.io/stdstack/auth-server:0.1
    container_name: stdstack-auth-server
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - config-server

